--- 
- 
  become: true
  hosts: all
  tasks: 
  
  - name: update cache 
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install nano & qemu-guest-agent 
    apt: 
       name:
       - nano
       - qemu-guest-agent
       state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install nano & qemu-guest-agent
    yum:
       name:
       - nano
       - qemu-guest-agent
       state: latest
    when: ansible_distribution == "CentOS"
