--- 
- 
  become: true
  hosts: all
  tasks: 
  
  - name: update cache 
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install nano 
    apt: 
       name: nano
       state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install qemu-gest-agent
    apt:
      name: qemu-guest-agent
      state: latest
    when: ansible_distribution == "Ubuntu"
